language: python
python:
  - "3.7"
  - "3.8"
# Travis doesn't support pypy5.6
#  - "pypy-5.6.0"
cache: pip
# command to install dependencies
install: pip install -U setuptools && pip install -U tox-travis
# command to run tests
script: python setup.py test
